# -*- coding: utf-8 -*-
"""
Medical Phonetic Dictionary for Indonesian TTS (Piper)
======================================================
Kamus ini memetakan kata-kata bahasa Inggris medis & operasional ke dalam
cara baca fonetik Indonesia (Indonesian phonetics) agar model TTS berbahasa 
Indonesia dapat mengucapkan kata bahasa Inggris tersebut dengan pelafalan 
yang terdengar seperti bahasa Inggris.

Kamus ini terdiri dari ~500 istilah yang dibagi menjadi 3 kategori:
1. Istilah Medis & Klinis (Medical & Clinical Terms)
2. Singkatan & Akronim Medis (Medical Abbreviations & Acronyms)
3. Alur Kerja, Teknologi & Bahasa Umum Rumah Sakit (Hospital Workflow, Tech & Daily Terms)
"""

MEDICAL_PHONETIC_DICT = {
    # ══════════════════════════════════════════════════════════════════════════
    # KATEGORI 1: ISTILAH MEDIS & KLINIS (Medical & Clinical Terms)
    # ══════════════════════════════════════════════════════════════════════════
    r"\babdomen\b": "eb do men",
    r"\babdominal\b": "eb do mi nel",
    r"\babnormal\b": "eb nor mel",
    r"\babortion\b": "e bor syen",
    r"\babrasion\b": "e brei jyen",
    r"\babscess\b": "eb ses",
    r"\baccident\b": "ek si dent",
    r"\bacute\b": "e kyut",
    r"\badenoid\b": "e de noid",
    r"\badhesion\b": "ed hi jyen",
    r"\badmission\b": "ed mi syen",
    r"\badmitting\b": "ed mi ting",
    r"\badrenal\b": "e dri nel",
    r"\badrenaline\b": "e dre ne lin",
    r"\ballergen\b": "e ler jen",
    r"\ballergic\b": "e ler jik",
    r"\ballergy\b": "e ler ji",
    r"\balopecia\b": "e lo pi sya",
    r"\balveolus\b": "el vi o lus",
    r"\balzheimer\b": "el zai mer",
    r"\bamnesia\b": "em ni sya",
    r"\bamputation\b": "em pyu tei syen",
    r"\banemia\b": "e ni mi ya",
    r"\banesthesia\b": "e nes thi jya",
    r"\banesthetic\b": "e nes the tik",
    r"\baneurysm\b": "e nyu ri zem",
    r"\bangina\b": "en jai na",
    r"\bangiography\b": "en ji og ra fi",
    r"\bangioplasty\b": "en ji o ples ti",
    r"\bantibiotic\b": "en ti bai o tik",
    r"\bantigen\b": "en ti jen",
    r"\bantioxidant\b": "en ti ok si den",
    r"\bantiseptic\b": "en ti sep tik",
    r"\banxiety\b": "eng zai e ti",
    r"\baorta\b": "ey or ta",
    r"\baphasia\b": "e fei jya",
    r"\bapnea\b": "ep ni ya",
    r"\bappendix\b": "e pen diks",
    r"\barrhythmia\b": "e rith mi ya",
    r"\barthritis\b": "ar thrai tis",
    r"\basthma\b": "ez ma",
    r"\bastigmatism\b": "es tig me ti zem",
    r"\batrophy\b": "e tro fi",
    r"\batrium\b": "ey tri yum",
    r"\bautism\b": "o ti zem",
    r"\bautopsy\b": "o top si",
    r"\baxilla\b": "ek si la",
    r"\bbacteria\b": "bek ti ri ya",
    r"\bbenign\b": "bi nain",
    r"\bbiopsy\b": "bai op si",
    r"\bbldad\b": "blad",
    r"\bbladder\b": "ble der",
    r"\bbleeding\b": "bli ding",
    r"\bblister\b": "blis ter",
    r"\bblood pressure\b": "blad pre syer",
    r"\bblood\b": "blad",
    r"\bbone\b": "boun",
    r"\bbowel\b": "bau el",
    r"\bbrain\b": "brein",
    r"\bbronchitis\b": "brong khai tis",
    r"\bbruise\b": "bruz",
    r"\bbypass\b": "bai pes",
    r"\bcaesarean\b": "si ze ri yen",
    r"\bcalculus\b": "kel kyu lus",
    r"\bcancer\b": "ken ser",
    r"\bcapillary\b": "ke pi le ri",
    r"\bcardiac\b": "kar diak",
    r"\bcardiology\b": "kar di o lo ji",
    r"\bcardiovascular\b": "kar di o ves kyu ler",
    r"\bcataract\b": "ke te rekt",
    r"\bcatheter\b": "ke the ter",
    r"\bcell\b": "sel",
    r"\bcerebellum\b": "se re be lum",
    r"\bcerebrum\b": "se re brem",
    r"\bcervix\b": "ser fiks",
    r"\bchemotherapy\b": "ki mo the ra pi",
    r"\bchest\b": "ces",
    r"\bchickenpox\b": "ci ken poks",
    r"\bchronic\b": "kro nik",
    r"\bcirrhosis\b": "si ro sis",
    r"\bclavicle\b": "kle fi kel",
    r"\bclinical\b": "kli ni kel",
    r"\bclotting\b": "klo ting",
    r"\bcoma\b": "ko ma",
    r"\bconcussion\b": "kon ka syen",
    r"\bcongenital\b": "kon je ni tel",
    r"\bcongestion\b": "kon jes tyen",
    r"\bconjunctivitis\b": "kon jung ti fai tis",
    r"\bconsciousness\b": "kon syes nes",
    r"\bconstipation\b": "kon sti pei syen",
    r"\bconsultation\b": "kon sul tei syen",
    r"\bcontagious\b": "kon tei jyes",
    r"\bcontraception\b": "kon tra sep syen",
    r"\bcontraction\b": "kon trek syen",
    r"\bcontusion\b": "kon tyu jyen",
    r"\bcornea\b": "kor ni ya",
    r"\bcoronary\b": "ko ro ne ri",
    r"\bcough\b": "kof",
    r"\bcramp\b": "kremp",
    r"\bcranium\b": "krei ni yum",
    r"\bcyst\b": "sist",
    r"\bdeafness\b": "def nes",
    r"\bdebridement\b": "di brid ment",
    r"\bdefibrillator\b": "di fi bri lei ter",
    r"\bdehydration\b": "di hai drei syen",
    r"\bdelirium\b": "di li ri yum",
    r"\bdelivery\b": "di li fe ri",
    r"\bdelusion\b": "di lyu jyen",
    r"\bdementia\b": "di men sya",
    r"\bdepression\b": "di pre syen",
    r"\bdermatitis\b": "der me thai tis",
    r"\bdermatology\b": "der me to lo ji",
    r"\bdermis\b": "der mis",
    r"\bdiabetes\b": "dai e bi tis",
    r"\bdiabetic\b": "dai e be tik",
    r"\bdiagnosis\b": "dai eg no sis",
    r"\bdialysis\b": "dai e li sis",
    r"\bdiarrhea\b": "dai e ri ya",
    r"\bdiastolic\b": "dai es to lik",
    r"\bdietitian\b": "dai e ti syen",
    r"\bdigestive\b": "di jes tiv",
    r"\bdisease\b": "di ziz",
    r"\bdislocation\b": "dis lo kei syen",
    r"\bdisorder\b": "dis or der",
    r"\bdizziness\b": "di zi nes",
    r"\bdoctor\b": "dok ter",
    r"\bdonor\b": "dou ner",
    r"\bdosage\b": "dou seij",
    r"\bdose\b": "dous",
    r"\bdrainage\b": "drei neij",
    r"\bdressing\b": "dre sing",
    r"\bdrugs\b": "draags",
    r"\bduodenum\b": "du o di nem",
    r"\bdyslexia\b": "dis lek sya",
    r"\bdyspepsia\b": "dis pep sya",
    r"\bdyspnea\b": "disp ni ya",
    r"\bear\b": "iyer",
    r"\beczema\b": "ek zi ma",
    r"\bedema\b": "i di ma",
    r"\bembolism\b": "em bo li zem",
    r"\bembryo\b": "em bri yo",
    r"\bemergency\b": "i mer jen si",
    r"\bendoscopy\b": "en dos ko pi",
    r"\bepidemic\b": "e pi de mik",
    r"\bepilepsy\b": "e pi lep si",
    r"\berythrocyte\b": "e rith ro sait",
    r"\besophagus\b": "i so fa gus",
    r"\bexhalation\b": "eks he lei syen",
    r"\beyeball\b": "ai bol",
    r"\beyelid\b": "ai lid",
    r"\bfacial\b": "fei syel",
    r"\bfatigue\b": "fe tig",
    r"\bfemur\b": "fi mer",
    r"\bfertility\b": "fer ti li ti",
    r"\bfetus\b": "fi tes",
    r"\bfever\b": "fi fer",
    r"\bfibula\b": "fi byu la",
    r"\bfracture\b": "frek tyer",
    r"\bgallbladder\b": "gol ble der",
    r"\bgallstone\b": "gol stoun",
    r"\bgastric\b": "ges trik",
    r"\bgastritis\b": "ges trai tis",
    r"\bgenetics\b": "je ne tiks",
    r"\bgeriatric\b": "je ri ye trik",
    r"\bgland\b": "glend",
    r"\bglaucoma\b": "glou ko ma",
    r"\bglucose\b": "glu kous",
    r"\bgout\b": "gaut",
    r"\bgraft\b": "greft",
    r"\bgynecology\b": "gai ne ko lo ji",
    r"\bheart\b": "hart",
    r"\bheart attack\b": "hat e tek",
    r"\bheartbeat\b": "hart bit",
    r"\bheartburn\b": "hart bern",
    r"\bhemoglobin\b": "hi mo glou bin",
    r"\bhemophilia\b": "hi mo fi li ya",
    r"\bhemorrhage\b": "he mo reij",
    r"\bhemorrhoid\b": "he mo roid",
    r"\bhepatitis\b": "he pe thai tis",
    r"\bhernia\b": "her ni ya",
    r"\bherpes\b": "her piz",
    r"\bhip\b": "hip",
    r"\bhormone\b": "hor moun",
    r"\bhumerus\b": "hyu me rus",
    r"\bhygiene\b": "hai jin",
    r"\bhyperactivity\b": "hai per ek ti vi ti",
    r"\bhyperglycemia\b": "hai per glai si mi ya",
    r"\bhypertension\b": "hai per ten syen",
    r"\bhyperventilation\b": "hai per ven ti lei syen",
    r"\bhypoglycemia\b": "hai po glai si mi ya",
    r"\bhypothermia\b": "hai po ther mi ya",
    r"\bhypoxia\b": "hai pok sya",
    r"\bhysterectomy\b": "his te rek to mi",
    r"\billness\b": "il nes",
    r"\bimmune\b": "i myun",
    r"\bimmunity\b": "i myu ni ti",
    r"\bimmunization\b": "i myu ni zei syen",
    r"\binfection\b": "in fek syen",
    r"\binfectious\b": "in fek syyes",
    r"\binflammation\b": "in fle mei syen",
    r"\binfluenza\b": "in flu en za",
    r"\binfusion\b": "in fyu jyen",
    r"\binhalation\b": "in he lei syen",
    r"\binhaler\b": "in hei ler",
    r"\binjection\b": "in jek syen",
    r"\binjury\b": "in ju ri",
    r"\binsomnia\b": "in som ni ya",
    r"\binsulin\b": "in syu lin",
    r"\bintestine\b": "in tes tin",
    r"\bintubation\b": "in tyu bei syen",
    r"\birritation\b": "i ri tei syen",
    r"\bischemia\b": "is ki mi ya",
    r"\bjaundice\b": "jon dis",
    r"\bjoint\b": "join",
    r"\bkidney\b": "kid ni",
    r"\bknee\b": "ni",
    r"\blaboratory\b": "le bo re to ri",
    r"\blarynx\b": "le rinks",
    r"\blesion\b": "li jyen",
    r"\bleukemia\b": "lu ki mi ya",
    r"\bleukocyte\b": "lu ko sait",
    r"\bligament\b": "li ge ment",
    r"\bliver\b": "li fer",
    r"\blungs\b": "langs",
    r"\blymph\b": "limf",
    r"\blymphoma\b": "lim fou ma",
    r"\bmalaria\b": "me le ri ya",
    r"\bmalignant\b": "me lig nent",
    r"\bmammogram\b": "me mo grem",
    r"\bmeasles\b": "mi zels",
    r"\bmedicine\b": "med sen",
    r"\bmelanoma\b": "me le nou ma",
    r"\bmembrane\b": "mem brein",
    r"\bmeningitis\b": "me nin jai tis",
    r"\bmenopause\b": "me no poz",
    r"\bmenstruation\b": "men stru ei syen",
    r"\bmetabolism\b": "me te bo li zem",
    r"\bmetastasis\b": "me tes te sis",
    r"\bmigraine\b": "mai grein",
    r"\bmuscle\b": "ma sel",
    r"\bnausea\b": "no zya",
    r"\bnerve\b": "nerf",
    r"\bneurology\b": "nyu ro lo ji",
    r"\bnurse\b": "ners",
    r"\bnutrition\b": "nyu tri syen",
    r"\bobesity\b": "o bi si ti",
    r"\bobstetrics\b": "ob ste triks",
    r"\boncology\b": "ong ko lo ji",
    r"\boperating room\b": "o pe rei ting rum",
    r"\boperation\b": "o pe rei syen",
    r"\bophthalmology\b": "of thel mo lo ji",
    r"\borthopedic\b": "or tho pi dik",
    r"\bosteoporosis\b": "os te o po rou sis",
    r"\boutpatient\b": "aut pei syent",
    r"\bovary\b": "o fa ri",
    r"\boxygen\b": "ok si jen",
    r"\bpacemaker\b": "peis mei ker",
    r"\bpainkiller\b": "pein ki ler",
    r"\bparalysis\b": "pe re li sis",
    r"\bparasite\b": "pe re sait",
    r"\bpathology\b": "pe tho lo ji",
    r"\bpatient\b": "pei syent",
    r"\bpediatric\b": "pi di ye trik",
    r"\bpelvis\b": "pel fis",
    r"\bpenicillin\b": "pe ni si lin",
    r"\bpharmacy\b": "far me si",
    r"\bphysician\b": "fi zi syen",
    r"\bphysiotherapy\b": "fi zi o the ra pi",
    r"\bplacebo\b": "ple si bou",
    r"\bplasma\b": "ples ma",
    r"\bplatelet\b": "pleit let",
    r"\bpneumonia\b": "nyu mou ni ya",
    r"\bpregnancy\b": "preg nen si",
    r"\bprescription\b": "pri skrip syen",
    r"\bprognosis\b": "prog nou sis",
    r"\bprostate\b": "pros teit",
    r"\bprosthetic\b": "pros the tik",
    r"\bpsychiatry\b": "sai kai e tri",
    r"\bpsychology\b": "sai ko lo ji",
    r"\bpulse\b": "pals",
    r"\bpus\b": "pas",
    r"\bquarantine\b": "kwo ren tin",
    r"\bradiation\b": "rei di ei syen",
    r"\bradiology\b": "rei di o lo ji",
    r"\brecovery\b": "ri ka fe ri",
    r"\breferral\b": "ri fe rel",
    r"\brehabilitation\b": "ri ha bi li tei syen",
    r"\brenal\b": "ri nel",
    r"\brespiration\b": "res pi rei syen",
    r"\bresuscitation\b": "ri sa si tei syen",
    r"\bsaliva\b": "se lai fa",
    r"\bscabies\b": "skei biz",
    r"\bscalpel\b": "skal puhl",
    r"\bscan\b": "sken",
    r"\bscapula\b": "ske pyu la",
    r"\bscar\b": "skar",
    r"\bscoliosis\b": "sko li o sis",
    r"\bscreening\b": "skri ning",
    r"\bsedative\b": "se de tiv",
    r"\bseizure\b": "si zher",
    r"\bsemen\b": "si men",
    r"\bsepsis\b": "sep sis",
    r"\bserum\b": "si rem",
    r"\bshingles\b": "sing gels",
    r"\bshock\b": "syok",
    r"\bside effect\b": "said i fek",
    r"\bsinus\b": "sinus",
    r"\bskeleton\b": "ske le ten",
    r"\bskin\b": "skin",
    r"\bskull\b": "skal",
    r"\bspasm\b": "spe zem",
    r"\bspecialist\b": "spe sya list",
    r"\bspecimen\b": "spe si men",
    r"\bspine\b": "spain",
    r"\bspleen\b": "splin",
    r"\bsputum\b": "spyu tem",
    r"\bsterile\b": "ste ril",
    r"\bstethoscope\b": "ste thos koup",
    r"\bstomach\b": "sto mek",
    r"\bstroke\b": "strok",
    r"\bsurgery\b": "ser je ri",
    r"\bsuture\b": "syu tyer",
    r"\bswelling\b": "swe ling",
    r"\bsymptom\b": "simp tem",
    r"\bsyndrome\b": "sin drom",
    r"\bsyringe\b": "si rinj",
    r"\bsystolic\b": "sis to lik",
    r"\btablet\b": "teb let",
    r"\btachycardia\b": "te khi kar di ya",
    r"\btendon\b": "ten den",
    r"\btestis\b": "tes tis",
    r"\btetanus\b": "te te nes",
    r"\btherapy\b": "the re pi",
    r"\btherapist\b": "the re pist",
    r"\bthermometer\b": "ther mo mi ter",
    r"\bthigh\b": "thai",
    r"\bthorax\b": "tho reks",
    r"\bthroat\b": "throut",
    r"\bthrombosis\b": "throm bou sis",
    r"\bthyroid\b": "thai roid",
    r"\btibia\b": "ti bi ya",
    r"\btissue\b": "ti syu",
    r"\btonsil\b": "ton sil",
    r"\btonsillitis\b": "ton si lai tis",
    r"\btoxic\b": "tok sik",
    r"\btoxicity\b": "tok si si ti",
    r"\btrachea\b": "trei ki ya",
    r"\btrauma\b": "trou ma",
    r"\btreatment\b": "triet ment",
    r"\btriage\b": "tri acs",
    r"\btuberculosis\b": "tyu ber kyu lou sis",
    r"\btumor\b": "tyu mer",
    r"\bulcer\b": "al ser",
    r"\bulna\b": "al na",
    r"\bultrasound\b": "al tra saund",
    r"\bunconscious\b": "an kon syyes",
    r"\burea\b": "yu ri ya",
    r"\bureter\b": "yu ri ter",
    r"\burethra\b": "yu ri thra",
    r"\burine\b": "yu rin",
    r"\buterus\b": "yu te rus",
    r"\bvaccination\b": "vek si nei syen",
    r"\bvaccine\b": "vek sin",
    r"\bvagina\b": "ve jai na",
    r"\bvalve\b": "felv",
    r"\bvaricose\b": "ve ri kous",
    r"\bvascular\b": "ves kyu ler",
    r"\bvasectomy\b": "ve sek to mi",
    r"\bvein\b": "vein",
    r"\bventilator\b": "ven ti lei ter",
    r"\bventricle\b": "ven tri kel",
    r"\bvertigo\b": "fer ti gou",
    r"\bvirus\b": "vai res",
    r"\bward\b": "wod",
    r"\bwheelchair\b": "wil cer",
    r"\bwound\b": "wund",
    r"\bwrist\b": "rist",
    r"\byeast\b": "yist",
    r"\bzygote\b": "zai gout",

    # ══════════════════════════════════════════════════════════════════════════
    # KATEGORI 2: SINGKATAN & AKRONIM MEDIS (Medical Abbreviations & Acronyms)
    # ══════════════════════════════════════════════════════════════════════════
    r"\baids\b": "eits",
    r"\bbp\b": "bi pi",
    r"\bbpm\b": "bi pi em",
    r"\bbun\b": "ban",
    r"\bcad\b": "si e di",
    r"\bcbc\b": "si bi si",
    r"\bchf\b": "si ec ef",
    r"\bckd\b": "si kei di",
    r"\bcns\b": "si en es",
    r"\bcopd\b": "si o pi di",
    r"\bcpr\b": "si pi ar",
    r"\bcrp\b": "si ar pi",
    r"\bcsf\b": "si es ef",
    r"\bct scan\b": "si ti sken",
    r"\bct-scan\b": "si ti sken",
    r"\bdna\b": "di en ei",
    r"\bdvt\b": "di fi ti",
    r"\becg\b": "i si ji",
    r"\beeg\b": "i i ji",
    r"\behr\b": "i ec ar",
    r"\bekg\b": "i kei ji",
    r"\bemg\b": "i em ji",
    r"\bemr\b": "i em ar",
    r"\bent\b": "i en ti",
    r"\ber\b": "i ar",
    r"\bfbs\b": "ef bi es",
    r"\bgcs\b": "ji si es",
    r"\bgerd\b": "gerd",
    r"\bgi\b": "ji ai",
    r"\bhba1c\b": "ec bi ei wan si",
    r"\bhb\b": "ec bi",
    r"\bhcv\b": "ec si fi",
    r"\bhdl\b": "ec di el",
    r"\bhiv\b": "ec ai fi",
    r"\bhr\b": "ec ar",
    r"\bicu\b": "ai si yu",
    r"\biv\b": "ai fi",
    r"\biv drip\b": "ai fi drip",
    r"\biv-drip\b": "ai fi drip",
    r"\bldl\b": "el di el",
    r"\blft\b": "el ef ti",
    r"\bmap\b": "mep",
    r"\bmdr\b": "em di ar",
    r"\bmri\b": "em er ai",
    r"\bmrsa\b": "em ar es ei",
    r"\bnicu\b": "ni kyu",
    r"\bnsaid\b": "en se id",
    r"\botc\b": "o ti si",
    r"\bpacs\b": "peks",
    r"\bpicu\b": "pi kyu",
    r"\bpts\b": "pi ti es",
    r"\brbc\b": "ar bi si",
    r"\brft\b": "ar ef ti",
    r"\brna\b": "ar en ei",
    r"\brr\b": "ar ar",
    r"\brx\b": "areks",
    r"\bsgot\b": "es ji o ti",
    r"\bsgpt\b": "es ji pi ti",
    r"\bstd\b": "es te di",
    r"\btb\b": "ti bi",
    r"\btsh\b": "ti es ec",
    r"\busg\b": "yu es ji",
    r"\buti\b": "yu ti ai",
    r"\bwbc\b": "dabelyu bi si",
    r"\bwho\b": "dabelyu ec o",
    r"\bxray\b": "eks rey",
    r"\bx-ray\b": "eks rey",
    r"\bpcr\b": "pi si ar",
    r"\bswab\b": "suap",
    r"\brdt\b": "er de te",
    r"\bav shunt\b": "ey fi syant",
    r"\bdka\b": "di kei ei",
    r"\blvedp\b": "el fi i di pi",
    r"\bef\b": "i ef",
    r"\bco2\b": "si o tu",
    r"\bo2\b": "o tu",
    r"\bph\b": "pi ec",
    r"\bsp2\b": "es pi tu",
    r"\bspo2\b": "es pi o tu",
    r"\bbmd\b": "bi em di",
    r"\bcabg\b": "ke bej",
    r"\bcva\b": "si vi ei",
    r"\bd&c\b": "di en si",
    r"\besrd\b": "i es ar di",
    r"\bibs\b": "ai bi es",
    r"\biddm\b": "ai di di em",
    r"\biud\b": "ai yu di",
    r"\bivf\b": "ai vi ef",
    r"\bng tube\b": "en ji tyub",
    r"\bng-tube\b": "en ji tyub",
    r"\bns\b": "en es",
    r"\borstat\b": "or stet",
    r"\bpft\b": "pi ef ti",
    r"\bpid\b": "pi ai di",
    r"\bpms\b": "pi em es",
    r"\bptsd\b": "pi ti es di",
    r"\bsad\b": "sed",
    r"\bsob\b": "es o bi",
    r"\btia\b": "ti ai ei",
    r"\btpa\b": "ti pi ei",
    r"\bu/a\b": "yu ei",
    r"\baid\b": "eyd",

    # ══════════════════════════════════════════════════════════════════════════
    # KATEGORI 3: ALUR KERJA, TEKNOLOGI & BAHASA UMUM (Workflow, Tech & Daily)
    # ══════════════════════════════════════════════════════════════════════════
    r"\bbattery\b": "be te ri",
    r"\bactive\b": "ek tif",
    r"\bnon-active\b": "non ek tif",
    r"\bactivate\b": "ek ti fet",
    r"\bdeactivate\b": "di ek ti fet",
    r"\bbring\b": "bring",
    r"\bdevice\b": "di fais",
    r"\bplease\b": "plis",
    r"\bme\b": "mi",
    r"\bhow\b": "hau",
    r"\bpull\b": "pul",
    r"\bmode\b": "moud",
    r"\bonline\b": "onlain",
    r"\boffline\b": "oflain",
    r"\bstandby\b": "sten bay",
    r"\bdownload\b": "daun loud",
    r"\bupload\b": "ap loud",
    r"\bupdate\b": "ap det",
    r"\bupgrade\b": "ap gred",
    r"\bclear\b": "klir",
    r"\bstand by\b": "sten bay",
    r"\bzero touch\b": "zirow tacs",
    r"\bzero-touch\b": "zirow tacs",
    r"\bhello\b": "helow",
    r"\bsuccess\b": "sak ses",
    r"\bwarning\b": "wor ning",
    r"\berror\b": "er or",
    r"\bfail\b": "feil",
    r"\bwaiting\b": "wei ting",
    r"\bsync\b": "singk",
    r"\bdatabase\b": "dei ta beis",
    r"\bserver\b": "ser fer",
    r"\bclient\b": "klai yen",
    r"\buser\b": "yu ser",
    r"\blogin\b": "lo gin",
    r"\blogout\b": "log aut",
    r"\bpassword\b": "pes word",
    r"\badmin\b": "ad min",
    r"\bsystem\b": "sis tem",
    r"\bfile\b": "fail",
    r"\bfolder\b": "foul der",
    r"\bdata\b": "dei ta",
    r"\bnetwork\b": "net werk",
    r"\bconnection\b": "ko nek syen",
    r"\bhardware\b": "hard wer",
    r"\bsoftware\b": "soft wer",
    r"\bdevice\b": "di fais",
    r"\binput\b": "in put",
    r"\boutput\b": "aut put",
    r"\bscreen\b": "skrin",
    r"\bmonitor\b": "mo ni ter",
    r"\bkeyboard\b": "ki bord",
    r"\bmouse\b": "maus",
    r"\bprinter\b": "prin ter",
    r"\bcable\b": "kei bel",
    r"\bpower\b": "pau wer",
    r"\bcharge\b": "carj",
    r"\bsignal\b": "sig nel",
    r"\bwifi\b": "way fay",
    r"\binternet\b": "in ter net",
    r"\bcloud\b": "klaud",
    r"\bbackup\b": "bek ap",
    r"\brestore\b": "ri stor",
    r"\binstall\b": "in stol",
    r"\buninstall\b": "an in stol",
    r"\bconfig\b": "kon fig",
    r"\bsettings\b": "se tings",
    r"\bmenu\b": "me nyu",
    r"\bbutton\b": "ba ten",
    r"\bclick\b": "klik",
    r"\bselect\b": "se lek",
    r"\bsearch\b": "serc",
    r"\bfilter\b": "fil ter",
    r"\bsort\b": "sort",
    r"\bview\b": "vyu",
    r"\bedit\b": "e dit",
    r"\bcopy\b": "ko pi",
    r"\bpaste\b": "peist",
    r"\bshare\b": "ser",
    r"\bsend\b": "sen",
    r"\breceive\b": "ri sif",
    r"\bmail\b": "meil",
    r"\bmessage\b": "me seij",
    r"\bchat\b": "cet",
    r"\bcall\b": "kol",
    r"\bvideo\b": "fi di yo",
    r"\baudio\b": "o di yo",
    r"\bvoice\b": "vois",
    r"\bspeaker\b": "spi ker",
    r"\bmic\b": "maik",
    r"\bheadset\b": "hed set",
    r"\bcamera\b": "ke me ra",
    r"\bdisplay\b": "dis plei",
    r"\bprojector\b": "pro jek ter",
    r"\blight\b": "lait",
    r"\bsensor\b": "sen sor",
    r"\balarm\b": "e larm",
    r"\bref\b": "ref",
    r"\breferral\b": "ri fe rel",
    r"\breport\b": "ri port",
    r"\bchart\b": "cart",
    r"\bgraph\b": "gref",
    r"\btable\b": "tei bel",
    r"\bpage\b": "peij",
    r"\btext\b": "teks",
    r"\bimage\b": "i meij",
    r"\bphoto\b": "fou tou",
    r"\bdocument\b": "do kyu ment",
    r"\bpdf\b": "pi di ef",
    r"\bword\b": "werd",
    r"\bexcel\b": "ek sel",
    r"\bpowerpoint\b": "pau wer poin",
    r"\bapp\b": "ep",
    r"\bweb\b": "web",
    r"\bsite\b": "sait",
    r"\blink\b": "lingk",
    r"\bcode\b": "koud",
    r"\bkey\b": "ki",
    r"\btoken\b": "tou ken",
    r"\bid\b": "ai di",
    r"\bname\b": "neim",
    r"\bdate\b": "deit",
    r"\btime\b": "taim",
    r"\bstatus\b": "ste tus",
    r"\btype\b": "taip",
    r"\bvalue\b": "fe lyu",
    r"\bcount\b": "kaunt",
    r"\btotal\b": "tou tel",
    r"\baverage\b": "e fe reij",
    r"\bmin\b": "min",
    r"\bmax\b": "meks",
    r"\brange\b": "reinj",
    r"\bunit\b": "yu nit",
    r"\bgroup\b": "grup",
    r"\blist\b": "list",
    r"\bhistory\b": "his to ri",
    r"\blog\b": "log",
    r"\bnotes\b": "nouts",
    r"\bcomment\b": "ko ment",
    r"\binfo\b": "in fou",
    r"\bhelp\b": "help",
    r"\babout\b": "e baut",
    r"\bscissor\b": "si zer",
    r"\bseizure\b": "si zher",
    r"\bpanic attack\b": "pe nik e tek",
    r"\bpanic-attack\b": "pe nik e tek",
    r"\brontgen\b": "ront gen",
    r"\bscalpel\b": "skal puhl",
    r"\bblood\b": "blad",
    r"\bdownload\b": "daun loud",
    r"\bsurgery\b": "ser je ri",
    r"\band\b": "en",
    r"\bbecause\b": "bik oz"    
}
